runtime: nodejs20
service: fermentation-planner
entrypoint: node server/index.js
env: standard
instance_class: F1

handlers:
  - url: /api/.*
    script: auto
    secure: always

  - url: /.*
    static_files: client/dist/index.html
    upload: client/dist/index.html
    secure: always
